spring:
  application:
    name: joke-app
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
